server:
  port: 5001
spring:
  profiles:
    include: db, app, mybatis, auth, logging, undertow, redis
  mvc:
    throw-exception-if-no-handler-found: true

# 是否启动演示模式，无法修改数据
preview:
  enabled: false

